"""Core typed domain model and deterministic safety-policy primitives for DWI."""

from .domain import (
    ActionEligibility,
    ActivityState,
    CleanupCandidate,
    Confidence,
    Evidence,
    EvidenceBundle,
    EvidencePolarity,
    EvidenceRequirement,
    NodeKind,
    ObservationStatus,
    ObservedNode,
    ProtectionClass,
    Provenance,
    ReclaimPriority,
    RegenerabilityState,
    RegenerationCost,
    ReachabilityState,
    RiskLabel,
    RuleOutcome,
    RuleTrace,
    RuleTraceEntry,
)
from .policy import SafetyContext, SafetyDecision, evaluate_safety, escalate_risk

__all__ = [
    "ActionEligibility",
    "ActivityState",
    "CleanupCandidate",
    "Confidence",
    "Evidence",
    "EvidenceBundle",
    "EvidencePolarity",
    "EvidenceRequirement",
    "NodeKind",
    "ObservationStatus",
    "ObservedNode",
    "ProtectionClass",
    "Provenance",
    "ReclaimPriority",
    "RegenerabilityState",
    "RegenerationCost",
    "ReachabilityState",
    "RiskLabel",
    "RuleOutcome",
    "RuleTrace",
    "RuleTraceEntry",
    "SafetyContext",
    "SafetyDecision",
    "escalate_risk",
    "evaluate_safety",
]
