"""Core typed domain model and deterministic safety-policy primitives for DWI."""

from .domain import (
    ActionEligibility,
    ActivityState,
    CleanupCandidate,
    Confidence,
    Evidence,
    EvidenceBundle,
    EvidencePolarity,
    EvidenceRequirement,
    NodeKind,
    ObservationStatus,
    ObservedNode,
    ProtectionClass,
    Provenance,
    ReclaimPriority,
    RegenerabilityState,
    RegenerationCost,
    ReachabilityState,
    RiskLabel,
    RuleOutcome,
    RuleTrace,
    RuleTraceEntry,
)
from .policy import SafetyContext, SafetyDecision, evaluate_safety, escalate_risk
from .contracts import (
    ArtifactKind,
    Ecosystem,
    EvidenceAssessment,
    EvidenceContract,
    all_contracts,
    contract_for,
)
from .fixtures import (
    ExpectedDomainInterpretation,
    SyntheticArtifactFixture,
    fixture_by_id,
    initial_artifact_fixtures,
)
from .pycache import PycacheDetection, PycacheInterpretation, inspect_pycache, interpret_pycache

__all__ = [
    "ActionEligibility",
    "ActivityState",
    "CleanupCandidate",
    "Confidence",
    "Evidence",
    "EvidenceBundle",
    "EvidencePolarity",
    "EvidenceRequirement",
    "NodeKind",
    "ObservationStatus",
    "ObservedNode",
    "ProtectionClass",
    "Provenance",
    "ReclaimPriority",
    "RegenerabilityState",
    "RegenerationCost",
    "ReachabilityState",
    "RiskLabel",
    "RuleOutcome",
    "RuleTrace",
    "RuleTraceEntry",
    "SafetyContext",
    "SafetyDecision",
    "escalate_risk",
    "evaluate_safety",
    "ArtifactKind",
    "Ecosystem",
    "EvidenceAssessment",
    "EvidenceContract",
    "all_contracts",
    "contract_for",
    "ExpectedDomainInterpretation",
    "SyntheticArtifactFixture",
    "fixture_by_id",
    "initial_artifact_fixtures",
    "PycacheDetection",
    "PycacheInterpretation",
    "inspect_pycache",
    "interpret_pycache",
]
