"""Core typed domain model and deterministic safety-policy primitives for DWI."""

from .domain import (
    ActionEligibility,
    ActivityState,
    CleanupCandidate,
    Confidence,
    Evidence,
    EvidenceBundle,
    EvidencePolarity,
    EvidenceRequirement,
    NodeKind,
    ObservationStatus,
    ObservedNode,
    ProtectionClass,
    Provenance,
    ReclaimPriority,
    RegenerabilityState,
    RegenerationCost,
    ReachabilityState,
    RiskLabel,
    RuleOutcome,
    RuleTrace,
    RuleTraceEntry,
)
from .policy import SafetyContext, SafetyDecision, evaluate_safety, escalate_risk
from .contracts import (
    ArtifactKind,
    Ecosystem,
    EvidenceAssessment,
    EvidenceContract,
    all_contracts,
    contract_for,
    requirements_by_key,
)
from .fixtures import (
    ExpectedDomainInterpretation,
    SyntheticArtifactFixture,
    fixture_by_id,
    initial_artifact_fixtures,
)
from .pycache import PycacheDetection, PycacheInterpretation, inspect_pycache, interpret_pycache
from .pytest_cache import (
    PytestCacheDetection,
    PytestCacheInterpretation,
    inspect_pytest_cache,
    interpret_pytest_cache,
)
from .mypy_cache import (
    MypyCacheDetection,
    MypyCacheInterpretation,
    inspect_mypy_cache,
    interpret_mypy_cache,
)
from .ruff_cache import (
    RuffCacheDetection,
    RuffCacheInterpretation,
    inspect_ruff_cache,
    interpret_ruff_cache,
)
from .venv import (
    PythonVenvDetection,
    PythonVenvInterpretation,
    inspect_python_venv,
    interpret_python_venv,
)
from .node_artifacts import (
    BuildArtifactDetection,
    BuildArtifactInterpretation,
    NextBuildDetection,
    NextBuildInterpretation,
    NodeArtifactDetection,
    NodeArtifactInterpretation,
    NodeModulesDetection,
    NodeModulesInterpretation,
    inspect_build,
    inspect_dist,
    inspect_next_build,
    inspect_node_modules,
    interpret_build,
    interpret_dist,
    interpret_next_build,
    interpret_node_modules,
)
from .dispatcher import AnalysisResult, analyze_candidate, dispatch_analysis
from .pipeline import CandidateEligibility, CandidateSelection, Finding, evaluate_analysis, select_candidate
from .size import SizeObservation, collect_size
from .scanner import WorkspaceScan, WorkspaceScanError, WorkspaceSummary, scan_workspace
from .report import (
    finding_to_dict,
    json_report,
    json_system_report,
    scan_to_dict,
    system_to_dict,
    table_report,
    table_system_report,
)
from .git_context import GitContextObservation, GitObjectForm, observe_git_path
from .global_storage import GlobalStorageDetection, GlobalStorageInterpretation, inspect_global_storage, interpret_global_storage
from .scan_control import ScanBudget, ScanLimits, ScanTermination
from .system_scan import (
    RootBoundary,
    RootObservation,
    RootRequest,
    RootScope,
    RootStatus,
    SystemScan,
    SystemScanError,
    SystemScanOptions,
    SystemSummary,
    approved_global_storage_roots,
    classify_root,
    scan_system,
)

__all__ = [
    "ActionEligibility",
    "ActivityState",
    "CleanupCandidate",
    "Confidence",
    "Evidence",
    "EvidenceBundle",
    "EvidencePolarity",
    "EvidenceRequirement",
    "NodeKind",
    "ObservationStatus",
    "ObservedNode",
    "ProtectionClass",
    "Provenance",
    "ReclaimPriority",
    "RegenerabilityState",
    "RegenerationCost",
    "ReachabilityState",
    "RiskLabel",
    "RuleOutcome",
    "RuleTrace",
    "RuleTraceEntry",
    "SafetyContext",
    "SafetyDecision",
    "escalate_risk",
    "evaluate_safety",
    "ArtifactKind",
    "Ecosystem",
    "EvidenceAssessment",
    "EvidenceContract",
    "all_contracts",
    "contract_for",
    "requirements_by_key",
    "ExpectedDomainInterpretation",
    "SyntheticArtifactFixture",
    "fixture_by_id",
    "initial_artifact_fixtures",
    "PycacheDetection",
    "PycacheInterpretation",
    "inspect_pycache",
    "interpret_pycache",
    "PytestCacheDetection",
    "PytestCacheInterpretation",
    "inspect_pytest_cache",
    "interpret_pytest_cache",
    "MypyCacheDetection",
    "MypyCacheInterpretation",
    "inspect_mypy_cache",
    "interpret_mypy_cache",
    "RuffCacheDetection",
    "RuffCacheInterpretation",
    "inspect_ruff_cache",
    "interpret_ruff_cache",
    "PythonVenvDetection",
    "PythonVenvInterpretation",
    "inspect_python_venv",
    "interpret_python_venv",
    "NodeArtifactDetection",
    "NodeArtifactInterpretation",
    "NodeModulesDetection",
    "NodeModulesInterpretation",
    "BuildArtifactDetection",
    "BuildArtifactInterpretation",
    "NextBuildDetection",
    "NextBuildInterpretation",
    "inspect_node_modules",
    "interpret_node_modules",
    "inspect_dist",
    "interpret_dist",
    "inspect_build",
    "interpret_build",
    "inspect_next_build",
    "interpret_next_build",
    "AnalysisResult",
    "analyze_candidate",
    "dispatch_analysis",
    "CandidateEligibility",
    "CandidateSelection",
    "Finding",
    "evaluate_analysis",
    "select_candidate",
    "SizeObservation",
    "collect_size",
    "WorkspaceScan",
    "WorkspaceScanError",
    "WorkspaceSummary",
    "scan_workspace",
    "json_report",
    "finding_to_dict",
    "scan_to_dict",
    "table_report",
    "json_system_report",
    "system_to_dict",
    "table_system_report",
    "GitContextObservation",
    "GitObjectForm",
    "observe_git_path",
    "GlobalStorageDetection",
    "GlobalStorageInterpretation",
    "inspect_global_storage",
    "interpret_global_storage",
    "ScanBudget",
    "ScanLimits",
    "ScanTermination",
    "RootBoundary",
    "RootObservation",
    "RootRequest",
    "RootScope",
    "RootStatus",
    "SystemScan",
    "SystemScanError",
    "SystemScanOptions",
    "SystemSummary",
    "approved_global_storage_roots",
    "classify_root",
    "scan_system",
]
